services:
    wuzapi-server:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '${WUZAPI_PORT:-8080}:8080'
        environment:
            - WUZAPI_ADMIN_TOKEN=${WUZAPI_ADMIN_TOKEN:-your_admin_token_here}
            - DB_USER=${DB_USER:-wuzapi}
            - DB_PASSWORD=${DB_PASSWORD:-wuzapi}
            - DB_NAME=${DB_NAME:-wuzapi}
            - DB_HOST=${DB_HOST:-db}
            - DB_PORT=${DB_PORT:-5432}
            - TZ=${TZ:-Asia/Jakarta}
            - WEBHOOK_FORMAT=${WEBHOOK_FORMAT:-json}
            - SESSION_DEVICE_NAME=${SESSION_DEVICE_NAME:-WuzAPI}
            - WUZAPI_GLOBAL_WEBHOOK=${WUZAPI_GLOBAL_WEBHOOK:-false}
        depends_on:
            db:
                condition: service_healthy
        networks:
            - wuzapi-network
        restart: on-failure

    db:
        image: postgres:16
        environment:
            POSTGRES_USER: ${DB_USER:-wuzapi}
            POSTGRES_PASSWORD: ${DB_PASSWORD:-wuzapi}
            POSTGRES_DB: ${DB_NAME:-wuzapi}
        ports:
            - '${POSTGRES_PORT:-5432}:5432'
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - wuzapi-network
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U wuzapi']
            interval: 5s
            timeout: 5s
            retries: 5
        restart: always

networks:
    wuzapi-network:
        driver: bridge

volumes:
    db_data:
